### PR TITLE
New lesson files; outlines but no content

### PR DESCRIPTION
**Pull request by mjones01**
Added new lessons (00-06) needed for revised unit: Intro to Spatial Data & Data Management. New lessons have full YAML & Greybox header and the outline copied over but no content.  
Added template for yaml / Greybox for any future lesson additions. 
Delete old templates and example lessons from repo.  
Changed file names for the lessons that currently existed (next step-> copy that info over to current lessons in appropriate place & then delete the old lessons).

### CODE REVIEW

**Comment by mjones01** [comment]
@lwasser  I forgot the NEONDataSkills doesn't have an account.  Can you grant me writing privileges for this repo and/or accept this PR?

**Comment by mjones01** [comment]
NOTE: There is now minimal content in the lessons. Copied from existing lessons.  All lessons need to be fleshed out significantly.

**Comment by lwasser** [comment]
you should have access now @mjones01

**Comment by mjones01** [comment]
Thank you.

**Pull request merged**
