### PR TITLE
diff on the lesson updates with the new template 

### PR DESCRIPTION
**Pull request by lwasser**

### CODE REVIEW

**Comment by fmichonneau** [comment]
Can this be closed now that I'm (almost) done converting the lesson to the SWC template?

**Comment by lwasser** [comment]
hey @fmichonneau the only thing this has is some updates to the lesson structure that i worked on. it's pretty much impossible to see with all of the files... 

i'm happy to add the new structure in a new PR with JUST THOSE FILES?? does that make sense?

**Comment by fmichonneau** [comment]
You can definitely create a new PR with just these files, or I can try to dig through the commit history of this PR to bring over these changes.

**Comment by lwasser** [comment]
you know... given the CAC is doing a great job of reviewing everything now... i wonder if i should just submit a PR for them to see what i started... BUT maybe it all gets rewritten in the end so it's not worth you digging through the history.

**Comment by lwasser** [comment]
i'm not super concerned about the history of just my edits. i was just working through things... and my fork needs a total update with the new awesome template work you did and there's lots of conflicts.

**Pull request closed without merging**
